# Generated by Django 5.1.3 on 2024-12-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('restante', models.IntegerField()),
                ('valor', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('valor', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('costo', models.FloatField(max_length=10)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('costo', models.FloatField(max_length=10)),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.filamento')),
            ],
        ),
    ]
