# Generated by Django 5.1.3 on 2024-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamento',
            name='restante',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
