# Generated by Django 5.1.3 on 2024-12-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='filamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produccion.filamento'),
            preserve_default=False,
        ),
    ]
