# Generated by Django 5.1.3 on 2024-11-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_filamento_restante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamento',
            name='restante',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
