# Generated by Django 5.1.3 on 2024-11-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_filamento_restante_alter_filamento_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamento',
            name='restante',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='valor',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='valor',
            field=models.FloatField(max_length=10),
        ),
    ]
