# Generated by Django 5.1.3 on 2024-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_filamento_restante_alter_filamento_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamento',
            name='restante',
            field=models.IntegerField(),
        ),
    ]
