# Generated by Django 5.1.3 on 2024-11-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_alter_filamento_restante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('tiempo', models.FloatField()),
                ('filamento', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
            ],
        ),
    ]
