# Generated by Django 5.1.3 on 2024-11-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_costocalculadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costocalculadora',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
