# Generated by Django 5.1.3 on 2024-11-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_calculo_delete_calculadoraproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
