# Generated by Django 5.1.3 on 2024-11-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_calculo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
