# Generated by Django 5.1.3 on 2024-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_alter_calculo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
