# Generated by Django 5.1.3 on 2024-12-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_alter_calculo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='filamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.filamento'),
        ),
    ]
