# Generated by Django 5.1.3 on 2024-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_alter_calculo_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='costo',
            field=models.FloatField(max_length=10),
        ),
    ]
