# Generated by Django 5.1.3 on 2024-12-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_remove_calculo_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='costo',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
