# Generated by Django 5.1.3 on 2024-12-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_calculo_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('costo', models.FloatField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('valor', models.FloatField(max_length=10)),
            ],
        ),
    ]
